name: Enable auto-merge

on:
  schedule:
    - cron: 0 * * * *
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

permissions: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: reitermarkus/automerge@634d0a4b51134c163eee182ac9aa79133eb33e8d # v2.8.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
          merge-method: squash
          squash-commit-title: ${pull_request.title} (#${pull_request.number})
          pull-request: ${{ github.event.inputs.pull-request }}
          pull-request-author-associations: COLLABORATOR,OWNER
          review: ${{ github.event.inputs.review }}
          review-author-associations: COLLABORATOR,OWNER
