name: Bump casks on schedule or request

on:
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    - cron: "15 */2 * * *"

permissions:
  contents: read

jobs:
  autobump:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          cask: false
          core: false
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'fuyunohoshi' }}

      - name: Get list of autobump casks
        id: autobump
        run: echo "autobump_list=$(brew tap-info p-linnane/cask-unsigned --json | jq -c -r '.[0]["cask_tokens"]|join(" ")')" >> "$GITHUB_OUTPUT"

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ secrets.BOT_TOKEN }}
          casks: ${{ github.event.inputs.casks || steps.autobump.outputs.autobump_list }}
